# Default values for my_proj.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

images:
  repository_httpd: httpd
  repository_nginx: nginx
  repository_mysql: mysql


service:
  type: ClusterIP
  port: 80
  targetPort: 80



resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 100m
     memory: 100Mi
   requests:
     cpu: 10m
     memory: 100Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
  - name: config
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: config
    mountPath: "/etc/app"
#   readOnly: true

nodeSelector: app1
container_mysql_port: 3306
container_port: 80



deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

ingress:
  enable: false
  host20: "web20.rtgk8s.link"
  host30: "web30.rtgk8s.link"
  port: 80
  path: "/"
  class: "nginx"


#postgresql:
 # auth:
  #  username: admin
   # password: admin
  # Other PostgreSQL configurations


mysql:
  auth:
    password: "YWRtaW4="
  # Other MySQL configurations
sql_volumeMounts:
  name: config-volume
  mountPath: /docker-entrypoint-initdb.d
mysql_volumes:
  name: config-volume
  configMap_name: mysql-config