apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
    - host: {{ .Values.ingress.host20 }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service-v2
                port:
                  number: {{ .Values.ingress.port }}
    - host: {{ .Values.ingress.host30 }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service-v3
                port:
                  number: {{ .Values.ingress.port }}
